- name: 创建 kubernetes 相关目录
  file: 
    name: "{{ item }}"
    state: directory
  with_items:
  - "{{ kubelet_root_dir }}"
  - /etc/kubernetes/pki
  - /etc/kubernetes/manifests
  - /usr/share/bash-completion/completions

- name: 读取 kubelet.conf 文件 stat 信息
  stat: 
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- name: 生成 kubelet systemd init 文件
  template: 
    src: 20-kubelet-override.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/20-kubelet-override.conf
    owner: root
    mode: 0644
  register: kubelet_systemd_init_result
- name: 重新加载 daemon
  systemd:
    daemon_reload: yes
  when: kubelet_systemd_init_result.changed

# 生成 kubeadm 配置
- include_tasks: kubeadm-config.yml

# 初始化第一个 master 节点
- include_tasks: master-init.yml
  when: 
  - not kubelet_conf_stat.stat.exists
  - inventory_hostname == groups['kube-master'][0]

# 初始化其他 master 节点
- include_tasks: master-join.yml
  when: 
  - not kubelet_conf_stat.stat.exists
  - inventory_hostname != groups['kube-master'][0]
  - inventory_hostname in (groups['kube-master'] + groups['new-master'])

- name: 确认 kubelet 配置是否有修改
  template:
    src: kubelet-config.v1beta1.yaml.j2
    dest: /var/lib/kubelet/config.yaml
    owner: root
    mode: 0644
  register: configuration_result

- name: 启动/重启 kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes
  when: kubelet_systemd_init_result.changed or configuration_result.changed